#MODEL=${MODEL:-"/software/data/pytorch/huggingface/hub/models--Qwen--Qwen3.5-0.8B/snapshots/2fc06364715b967f1860aea9cf38778875588b17/"}
#MODEL=${MODEL:-"/software/data/pytorch/huggingface/hub/models--Qwen--Qwen3.5-35B-A3B-FP8/snapshots/0b2752837483aa34b3db6e83e151b150c0e00e49/"}
MODEL=${MODEL:-"/software/data/pytorch/huggingface/hub/models--Qwen--Qwen3.5-35B-A3B/snapshots/ec2d4ece1ffb563322cbee9a48fe0e3fcbce0307/"}  

VLLM_USE_HYBRID_CACHE=true \
VLLM_USE_NAIVE_MAMBA_CACHE_SHARING=false \
VLLM_FP32_SOFTMAX=true \
VLLM_GRAPH_RESERVED_MEM=0.3 \
VLLM_LOGGING_LEVEL=DEBUG \
TRANSFORMERS_VERBOSITY=info \
VLLM_EXPONENTIAL_BUCKETING=false \
VLLM_BUCKETING_STRATEGY=linear_bucketing \
VLLM_PROMPT_QUERY_BUCKET_MIN=128 \
VLLM_PROMPT_QUERY_BUCKET_STEP=128 \
VLLM_PROMPT_QUERY_BUCKET_MAX=256 \
VLLM_PROMPT_CTX_BUCKET_MIN=0 \
VLLM_PROMPT_CTX_BUCKET_STEP=1 \
VLLM_PROMPT_CTX_BUCKET_MAX=64 \
VLLM_FUSED_BLOCK_SOFTMAX_ADJUSTMENT=False \
PT_HPU_ENABLE_LAZY_COLLECTIVES=true \
EXPERIMENTAL_WEIGHT_SHARING=0 \
FUSER_ENABLE_LOW_UTILIZATION=true \
ENABLE_FUSION_BEFORE_NORM=true \
VLLM_SKIP_WARMUP=true \
VLLM_GRAPH_RESERVED_MEM=0.1 \
VLLM_CONTIGUOUS_PA=true \
VLLM_DEFRAG=true \
python test.py \
  --model $MODEL \
  --mode text \
  --max-model-len 16384 \
  --gpu-memory-utilization 0.5 \
  --max-num-batched-tokens 4096 \
  "$@" 2>&1 | tee log.txt

