# test_config.yaml
stages:
  - name: test_gsm8k_small_models
    steps:
      - name: gsm8k_small_g3_tp1_part1
        flavor: g3
        command: >-
          export PT_HPU_LAZY_MODE=0 && export VLLM_T_COMPILE_FULLGRAPH=True && 
          cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1
