name: Get PR Details
description: 'Retrieves pull request details for pull_request_target or merge_group events'

inputs:
  event_name:
    description: 'Event name that triggered the caller workflow'
    required: true
  pr_number:
    description: 'PR number for pull_request_target events'
    required: false
  merge_group_head_ref:
    description: 'Merge group head ref for merge_group events'
    required: false

outputs:
  pr_number:
    description: 'Pull request number'
    value: ${{ steps.get_pr_details.outputs.pr_number }}
  pr_title:
    description: 'Pull request title'
    value: ${{ steps.get_pr_details.outputs.pr_title }}
  pr_labels:
    description: 'Pull request labels (comma-separated)'
    value: ${{ steps.get_pr_details.outputs.pr_labels }}
  pr_base_ref:
    description: 'Pull request base reference'
    value: ${{ steps.get_pr_details.outputs.pr_base_ref }}
  skip_gaudi_tests:
    description: 'Whether to skip Gaudi tests'
    value: ${{ steps.get_pr_details.outputs.skip_gaudi_tests }}

runs:
  using: 'composite'
  steps:
    - name: Retrieve Pull Request information
      id: get_pr_details
      uses: actions/github-script@v7
      env:
        EVENT_NAME: ${{ inputs.event_name }}
        PR_NUMBER: ${{ inputs.pr_number }}
        MERGE_GROUP_HEAD_REF: ${{ inputs.merge_group_head_ref }}
      with:
        script: |
          const eventName = process.env.EVENT_NAME;

          console.log('Trigger event: %s', eventName);
          if (eventName === 'merge_group') {
              const headRef = process.env.MERGE_GROUP_HEAD_REF;
              
              if (!headRef || typeof headRef !== 'string') {
                  console.log('❌ MERGE_GROUP_HEAD_REF is missing or invalid. Received:', headRef);
                  core.setFailed('MERGE_GROUP_HEAD_REF is missing or invalid for merge_group event');
                  return;
              }
              
              const prMatch = headRef.match(/pr-(\d+)-/);
              
              if (!prMatch) {
                  console.log('❌ Merge group head ref does not match expected format "pr-<number>-...". Received:', headRef);
                  core.setFailed('Could not extract PR number from merge group head ref: unexpected format');
                  return;
              }
              
              const prNumber = parseInt(prMatch[1], 10);
              console.log('📋 Found source PR number: %s', prNumber);
              
              try {
                  const { data: pullRequest } = await github.rest.pulls.get({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: prNumber
                  });

                  const prLabels = pullRequest.labels.map(l => l.name).join(', ') || 'None';
                  
                  console.log('\n✅ Source Pull Request Information:');
                  console.log('- PR Number: #%s', pullRequest.number);
                  console.log('- PR Title: %s', pullRequest.title);
                  console.log('- PR Author: %s', pullRequest.user.login);
                  console.log('- PR State: %s', pullRequest.state);
                  console.log('- PR Labels: %s', prLabels);
                  
                  const skipGaudiTests = pullRequest.labels.some(l => l.name === 'skip-gaudi-tests');
                  
                  const fs = require('fs');
                  const outputFile = process.env.GITHUB_OUTPUT;
                  fs.appendFileSync(outputFile, `pr_number=${pullRequest.number}\n`);
                  fs.appendFileSync(outputFile, `pr_title=${pullRequest.title}\n`);
                  fs.appendFileSync(outputFile, `pr_labels=${prLabels}\n`);
                  fs.appendFileSync(outputFile, `pr_base_ref=${pullRequest.base.ref}\n`);
                  fs.appendFileSync(outputFile, `skip_gaudi_tests=${skipGaudiTests}\n`);
                  
              } catch (error) {
                  console.error('❌ Error fetching PR details:', error.message);
                  core.setFailed(error.message);
              }
          } else if (eventName === 'pull_request_target') {
              const prNumber = process.env.PR_NUMBER;
              
              try {
                  const { data: pullRequest } = await github.rest.pulls.get({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: prNumber
                  });

                  const prLabels = pullRequest.labels.map(l => l.name).join(', ') || 'None';
                  
                  console.log('\n✅ Pull Request Information:');
                  console.log('- PR Number: #%s', pullRequest.number);
                  console.log('- PR Title: %s', pullRequest.title);
                  console.log('- PR Author: %s', pullRequest.user.login);
                  console.log('- PR State: %s', pullRequest.state);
                  console.log('- PR Labels: %s', prLabels);
                  
                  const skipGaudiTests = pullRequest.labels.some(l => l.name === 'skip-gaudi-tests');
                  
                  const fs = require('fs');
                  const outputFile = process.env.GITHUB_OUTPUT;
                  fs.appendFileSync(outputFile, `pr_number=${pullRequest.number}\n`);
                  fs.appendFileSync(outputFile, `pr_title=${pullRequest.title}\n`);
                  fs.appendFileSync(outputFile, `pr_labels=${prLabels}\n`);
                  fs.appendFileSync(outputFile, `pr_base_ref=${pullRequest.base.ref}\n`);
                  fs.appendFileSync(outputFile, `skip_gaudi_tests=${skipGaudiTests}\n`);
                  
              } catch (error) {
                  console.error('❌ Error fetching PR details:', error.message);
                  core.setFailed(error.message);
              }
          } else {
              const errorMessage = "Event not supported. Use 'pull_request_target' or 'merge_group'.";
              console.error(errorMessage);
              core.setFailed(errorMessage);
          }
