nav:
  - Home: 
    - vLLM Hardware Plugin for Intel® Gaudi®: README.md
    - Getting Started:
      - Quick Start: 
        - getting_started/quickstart.md
        - getting_started/quickstart_configuration.md
        - getting_started/quickstart_inference.md
      - Installation: getting_started/installation.md
    - Quick Links:
      - User Guide: user_guide/README.md
      - Developer Guide: dev_guide/README.md
      - API Reference: api/README.md
  - User Guide:
    - Summary: user_guide/README.md
    - user_guide/v1_guide.md
    - General:
      - user_guide/*
    - Configuration:
      - Summary: configuration/README.md
      - configuration/env_vars.md
      - configuration/long_context.md
      - configuration/model_calibration.md
      - configuration/optimization.md
      - configuration/pipeline_parallelism.md
      #- configuration/*
    - Models:
      - models/validated_models.md
    - Features:
      - features/supported_features.md
      - features/compatibility_matrix.md
      - features/*
      - features/quantization
  - Developer Guide:
    - Summary: dev_guide/README.md
    - General:
      - dev_guide/ci-failures.md
      - Profiling:
        - Summary: dev_guide/profiling/profiling.md
        - dev_guide/profiling/e2e-profiling.md
        - dev_guide/profiling/high-level-profiling.md
        - dev_guide/profiling/pytorch-profiling-async.md
        - dev_guide/profiling/pytorch-profiling-script.md
        - dev_guide/profiling/profiling-prompt-decode.md
    - Design Documents:
      - design/*
  - API Reference:
    - Summary: api/README.md
    - Contents:
      - glob: api/vllm_gaudi/*
        preserve_directory_names: true